language: android

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-21
  licenses:
    - android-sdk-license-5be876d5
    - android-sdk-license-c81a61d9

script:
  - ./gradlew clean test
